config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :messages do
    resources :comments
  end

  root to: 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  message_id :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_message_id  (message_id)
#  index_comments_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (message_id => messages.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_messages_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  has_many :messages
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message
  before_action :set_comment, except: %i[create]
  before_action :check_owner, only: %i[edit update destroy]

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end

  private

  def set_message
    @message = Message.find(params[:message_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def check_owner
    redirect_to message_path(@message), notice: 'No puedes editar un comentario que no es tuyo' unless current_user.id == @comment.user_id
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

# messages controller
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_message, only: %i[show edit update destroy]

  def index
    @messages = Message.all.order(created_at: :desc)
  end

  def show; end

  def new
    @message = current_user.messages.build
  end

  def edit; end

  def create
    @message = current_user.messages.build(message_params)
    
    if @message.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render :edit
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-content"><%= comment.content %></p>
  <p class="comment-posted-by">By: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>
  <div class="links">
    <% if user_signed_in? && current_user.id == comment.user_id %>
      <%= link_to 'Edit', edit_message_comment_path(comment.message, comment), class: 'btn btn-warning' %>
      <%= link_to 'delete', message_comment_path(comment.message, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: 'comments', class: 'form-control' %>
  <%= f.submit :submit, class: 'btn btn-primary' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
  <%= f.input :content, label: 'comments', class: 'form-control' %>
  <%= f.submit :submit, class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Espn</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to 'ESPN FAN FORUM', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!--<li class="nav-item">
          <%#= link_to 'ESPN FAN FORUM', root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>-->
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Post It', new_message_path, class: 'btn btn-primary' %></li>
            <li class="nav-item"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to 'Log In', new_user_session_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message", class: 'form-control' %>
  <%= f.input :description, class: 'form-control' %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/messages/edit.html.erb
<div class="row">
  <div class="offset-md-2 col-md-8">
    <h1 class="new-msg-header">Fix Message</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
  <div class="row">
    <div class="offset-md-1 col-md-10">
      <div class="message">
        <h2 class="message-title"><%= message.title %></h2>
        <%= link_to 'join convo', message, class: 'badge rounded-pill text-bg-warning' %>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/new.html.erb
<div class="row">
  <div class="offset-md-2 col-md-8">
    <h1 class="new-msg-header">Post Message</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/messages/show.html.erb
<div class="row">
  <div class="offset-md-1 col-md-10">
    <div class="message-show">
      <h2><%= @message.title %></h2>
      <p class="message-posted-by"><%= time_ago_in_words(@message.created_at) %> ago</p>
      <p class="message-desc"><%= @message.description %></p>
      <div class="links btn-group mb-5">
        <%= link_to 'Back', root_path, class: 'btn btn-primary' %>
        <% if user_signed_in? && current_user.id == @message.user_id %>
          <%= link_to 'Fix', edit_message_path(@message), class: 'btn btn-warning' %>
          <%= link_to 'Delete', message_path(@message), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
      </div>

      <h3 class="comments-section-header">Comments:</h3>
      <p><%= render @message.comments.includes(:user) %></p>
      <h3 class="reply-to-msg">Join Discussion:</h3>
      <%= render 'comments/form' %>
    </div>
  </div>
</div>